### ISSUE TITLE
Use supported Language annotations

### ISSUE THREAD

**Issue by Proximyst** [aikar/db#12]
The language in `@Language` annotations is not `MySQL` but rather just `SQL` in IntelliJ. As it stands, the annotations are useless to IntelliJ users (which is the IDE they were made for, or so I assume due to the `org.intellij.lang.annotations` package) as `MySQL` is not a recognised language.

**Comment by aikar** [comment]
It appears MySQL must only be valid for IntelliJ Ultimate, because it does work there. But looks like SQL works too, so good with me.
